@startuml ClassModel

skinparam monochrome reverse

package tictactoe{
    class TTTGame{
        -Board board
        -Round round
        -Statistic statistic
        -Player player1
        -Player player2
        -ArrayList<Player> playersList

        +void setup()
        +void execute()
        +void statistics()
        -void addPlayer()
        -void displayPlayers()
        -Player selectPlayer(int counter)
        -void setPlayers()
        -Player searchPlayer(int id)
    }

    class Player{
        -int id
        -String name
        -Mark mark

        +Player(String name)
        +Coordinate putMark()
    }

    class Round{
        -Board board
        -Player player1
        -Player player2
        -Statistic statistic

        +Round(Board board, Player player1, Player player2, Statistic statistic)
        +void executeRounds()
        -void executeTurn(Player player)
    }

    class Statistic{
        -ArrayList<String> statistics

        +void addStatistic(String message)
        +void displayStatistics()
    }

    package board{
        class Board{
            -int dimensions
            -Space[][] board

            +Board()
            -void initializeBoard()
            +void paint()
            +boolean validateChoice(Coordinate coordinate)
            +boolean verifyChoiceExistence()
            -boolean verifyColumns(Mark mark)
            -boolean verifyRows(Mark mark)
            -boolean verifyDiagonal(Mark mark)
            -boolean verifyReverseDiagonal(Mark mark)
            +boolean determineWinner(Mark mark)
            +void update(Mark mark, Coordinate coordinate)
        }

        class Space{
            -Mark mark
            -Coordinate coordinate

            +Space(Mark mark, Coordinate coordinate)
            +boolean isAvailable()
        }

        class Coordinate{
            -int positionX
            -int positionY

            +Coordinate(int positionX,int positionY)
        }
    }

    package utils{
        enum Mark{
            ZERO
            X
            EMPTY

            -String value

            +Mark(String value)
            +boolean isAvailable(Mark mark)
        }
    }
}

TTTGame *-left- Board
TTTGame *-- Player
TTTGame *-- Round
TTTGame *-- Statistic

Board *-- Space

Space *-- Coordinate

Round -left-> Board
Round -right-> Player

Statistic <-- Round

Player --> Mark
Space --> Mark

@enduml