@startuml DomainModel

skinparam monochrome reverse

object TTTGame
    object Board
        object dimensions
        object Spaces
            object Coordinate
                object positionX
                object positionY
    object BoardGoals
        object paint
        object validateChoice
        object verifyChoiceExistence
        object determineWinner
    object Player
        object id
        object name
        object mark
        object PlayerGoals
            object putPiece
    object Rounds
        object RoundGoals
            object executeRound
    object Mark
        object Zero
        object X
        object Empty
        object availability
    object Statistic
        object winnerName

TTTGame *-left- Board
TTTGame *-- Player
TTTGame *-- Rounds
TTTGame *-- Statistic

Board *-left- dimensions
Board *-- Spaces
Board o-- BoardGoals
BoardGoals <|-- paint
BoardGoals <|-- validateChoice
BoardGoals <|-- verifyChoiceExistence
BoardGoals <|-- determineWinner

Spaces *-- Coordinate
Spaces o-- Mark

Coordinate *-- positionX
Coordinate *-- positionY

Rounds o-- RoundGoals
Rounds --> Player
Rounds --> Board
RoundGoals <|-- executeRound

Player *-- id
Player *-- name
Player *-- Mark
Player o-- PlayerGoals
PlayerGoals <|-- putPiece

Mark <|-- Zero
Mark <|-- X
Mark <|-- Empty
Mark *-- availability

Statistic *-- winnerName
Statistic <-- Rounds


@enduml